### ISSUE TITLE
Crashes when attempting to set map

### ISSUE THREAD

**Issue by Rainee4563** [Shugabuga/Splatoon2RichPresence#2]
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Python37\lib\tkinter\__init__.py", line 746, in callit
    func(*args)
  File "C:\Users\mario\OneDrive\Desktop\Splatoon2RichPresence\launch.py", line 81, in <lambda>
    label.after(1000, lambda:loop(currentMap, start_time))
  File "C:\Users\mario\OneDrive\Desktop\Splatoon2RichPresence\launch.py", line 79, in loop
    rpc_obj.set_activity(activity)
  File "C:\Users\mario\OneDrive\Desktop\Splatoon2RichPresence\core\rpc.py", line 138, in set_activity
    self.send(data)
  File "C:\Users\mario\OneDrive\Desktop\Splatoon2RichPresence\core\rpc.py", line 116, in send
    self._write(header)
  File "C:\Users\mario\OneDrive\Desktop\Splatoon2RichPresence\core\rpc.py", line 161, in _write
    self._f.flush()
OSError: [Errno 22] Invalid argument`

So when im attempting to set the map im playing that happens

**Comment by Shugabuga** [comment]
Are you using Windows by any chance? Might be a duplicate of #1, which I still have to investigate (as a macOS user).

**Comment by Rainee4563** [comment]
yes

**Comment by Shugabuga** [comment]
Okay. Seems like Windows support is completely broken, so I'l investigate as soon as I get the chance.
